# Accessing/Changing specific elements, rows, columns,etc

In [3]:
import numpy as np

In [4]:
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [5]:
a.shape

(2, 7)

In [ ]:
#get a specific element [r,c]
a[1,5]



In [ ]:
#get a specific element [r,-c]
a[1,-2]

20

In [ ]:
#get a specific Rrow
a[0,:]


array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#get a specific column
a[:,2]

array([1, 2])

In [ ]:
#getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [ ]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [ ]:
a[:,2]=5
print(a)
#or

a[:,2]=[1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#get specific element (work outside in)
b[0,1,1]


4

In [ ]:
#or
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [ ]:
#replace
b[:,1,:] = [[9,9],[8,8]]


In [ ]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [ ]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [ ]:
a[:,2]=20
print(a)

[[ 1  2 20  4  5]
 [ 6  7 20  9 10]]


# Initializing Different Types of Arryas

In [ ]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((2,3,3))

In [ ]:
np.zeros((2,3,3,2))

In [ ]:
#All 1s matrix
np.ones((4,2,2))


In [168]:
#All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
#any other number
np.full((2,2),99,dtype='float32')

In [6]:
#any other number (full_like)
np.full_like(a.shape,4)

array([4, 4])

In [7]:
#any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [8]:
#random decimal numbers
np.random.rand(4,2)

array([[0.9006397 , 0.42218439],
       [0.01259317, 0.17831276],
       [0.22415655, 0.38162448],
       [0.08228803, 0.97554039]])

In [ ]:
#random decimal numbers
np.random.rand(4,2,3)

In [ ]:
#random decimal numbers
np.random.random_sample(a.shape)

In [12]:
#random integer volues///
np.random.randint(7)

2

In [ ]:
#random integer volues///

np.random.randint(7,size=(3,3))

In [16]:
np.random.randint(4,7,size=(3,3))

array([[5, 6, 6],
       [6, 5, 6],
       [4, 5, 5]])

In [20]:
np.random.randint(-4,8,size=(3,3))

array([[ 7,  3, -1],
       [ 1,  0,  7],
       [ 1,  4,  6]])

In [22]:
#the identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
#repeot an array
arr =np.array([[1,2,3]])
r1=np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [30]:
#repeot an array
arr =np.array([[1,2,3]])
r1=np.repeat(arr,3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [ ]:
#الهدف منه هو دمج
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4] =z #في بداية نعد مكان صفوالعامود
print(output)

In [35]:
#الهدف منه هو دمج
output=np.ones((5,5))


z=np.zeros((3,3))
z[1,1]=9


output[1:-1,1:-1] =z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
output=np.zeros((7,7))
z=np.ones((5,5))
z[2,2]=5
output[1:-1,1:-1]=z
print(output)

Be careful when coping arrays

In [48]:
#copyفائدتها انو ماتتغير قيمتها
a=np.array([1,2,3])
b=a.copy()
b[0]=100
a


array([1, 2, 3])

In [50]:
a=np.array([1,2,3,4,5])
b=a
b[2]=20
b

array([ 1,  2, 20,  4,  5])

**Mathematics**

In [73]:
a= np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [52]:
a+2

array([3, 4, 5, 6])

In [69]:
a += 2
a

array([3, 4, 5, 6])

In [53]:
a-2

array([-1,  0,  1,  2])

In [54]:
a*2

array([2, 4, 6, 8])

In [55]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [74]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [75]:
a**2

array([ 1,  4,  9, 16])

In [76]:
# take the sin or cin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
#for a lot more (https://numpy.org/doc/stable/reference/routines.math.html)

**Linear Algebra**

In [80]:
#لازم تكون متساوية
a= np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [81]:
#find the dererminant
c=np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
# reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)
#determinant
#trace
#singuior vector decomposition
#eigenvalues
#matrix norm
#inverse
#etc

###statistics

In [82]:
stats= np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
np.min(stats)

1

In [85]:
np.min(stats,axis=1)

array([1, 4])

In [86]:
np.min(stats,axis=0)

array([1, 2, 3])

In [84]:
np.max(stats)

6

In [88]:
np.max(stats,axis=1)

array([3, 6])

In [90]:
np.sum(stats)

21

In [93]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [98]:
a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
b = np.max(a, axis=1).sum()
b

15

### Reorganizing Arrays

In [104]:
#الفائدة عشان نعيد ترتيبها
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after =before.reshape((8,1))
after

[[1 2 3 4]
 [5 6 7 8]]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [103]:
after =before.reshape((2,2,2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [109]:
#verically stacking vectors
#لازم تكون متساوية
v1= np.array([1,2,3,4])
v2= np.array([5,6,7,8])
np.vstack([v1,v2])
#or
np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [110]:
#horizontal stack
h1= np.ones((2,4))
h2= np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [112]:
aa = np.ones((2,4))
bb= aa.reshape((4,2))
bb

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

###**Miscellaneous**

Load Data from file

In [140]:
# لو مثلا انت تبغى ملف نصي فيه جميع البيانات ولا تبغى تستخدم  (pandas)
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata.astype('int32') #int
filedata# هنا ترجع الى الاصل بدون int , بس لو شلناه وحطينا int تطلع اعداد
#or
#filedata = filedata.astype('int32')
#filedata

array([  1.,   2.,   3.,   4.,   5.,   6.,  77.,  88.,   4.,   9.,  99.,
        66., 345.])

####boolten Masking and Adanced indexing

In [142]:
filedata>50

array([False, False, False, False, False, False,  True,  True, False,
       False,  True,  True,  True])

In [143]:
filedata[filedata>50]

array([ 77.,  88.,  99.,  66., 345.])

In [145]:
# you can indexwith a list in NumPy

aaa=np.array([1,2,3,4,5,6,7,8,9])
aaa[[1,2,8]]

array([2, 3, 9])

In [144]:
# لو ابغى اعرف اي قيمة اكبر من 50\\
np.any(filedata > 50,axis=0)

True

In [151]:
#//
np.all(filedata > 50 , axis=0)

False

In [154]:
#اكبر من 50 واقل من 100
((filedata>50)&(filedata<100))

array([False, False, False, False, False, False,  True,  True, False,
       False,  True,  True, False])

In [156]:
#لا  يزيد عن 50 ولا يقل عن 100
(~((filedata>50)&(filedata<100)))

array([ True,  True,  True,  True,  True,  True, False, False,  True,
        True, False, False,  True])

In [161]:
filedata = np.genfromtxt('data1.txt', delimiter=',')
filedata.astype('int32')

array([[ 29,  97,  32, 100,  45],
       [ 15,  88,   5,  75,  22]], dtype=int32)

In [167]:
filedata = np.genfromtxt('data1.txt', delimiter=',')
output = filedata[filedata < 50]
print(output)

[29. 32. 45. 15.  5. 22.]


In [169]:
q=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
q

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [170]:
q[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [175]:
q[[0,1,2,3,4],[0,1,2,3,4]]

array([ 1,  7, 13, 19, 25])

In [178]:
q[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [182]:
q[[0,1,2,3,4,5],1:2]

array([[ 2],
       [ 7],
       [12],
       [17],
       [22],
       [27]])