![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# LOAD in Numpy(remember to pip install numpy first)


In [2]:
import numpy as np


# The Basics

In [20]:
a=np.array([1,2,3],)

In [12]:
#تحديد النوع الذي نريد تخزينه فربما كنا نعلم اننا لا نملك الكثير من القيم الكبيرة, لذا تكون تشغيلها مساحة اقل
a=np.array([1,2,3], dtype='int16')

print(a)


[1 2 3]


In [5]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [18]:
#Get Dimnsion
a.ndim

2

In [9]:
# Get Shape
a.shape

(3,)

In [21]:
#نبغى نعرف مقدار الذاكرة التي يشغلها مجموعات Numpy ,النوع والحجم
#Get type
# لو ماحطينا في بداية 16 راح تكون 32
a.dtype



dtype('int64')

In [27]:
#Get size
#راح يطلع 2بيت لانو 16
a.itemsize

8

In [24]:
#get total size
a.size

6

In [26]:
#get total size
#a.size*a.itemize
a.nbytes

24